# Generated by Django 4.1.2 on 2022-10-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todolist_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='slno',
        ),
    ]
