# Generated by Django 4.1.2 on 2022-10-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_todolist_average_alter_todolist_num1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='average',
            field=models.IntegerField(default=0),
        ),
    ]
